name: Get latest release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/Mahdi-zarei/nekoray/releases/latest | jq -r ".tag_name" | sed 's~[^0-9\.]~~g' > nekoray.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@users.noreply.github.com'
          git add --all
          git commit -am "New release version"
          git push

